apiVersion: v1
kind: Service
metadata:
  name: jenkins-react-application-service
spec:
  type: NodePort
  selector:
    app: jenkins-practice-react-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

